name: Python (yarn) tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  DB: postgres

jobs:
  test:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        db-type: [postgres, sqlite]

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: nextcloudappstore
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install gettext netcat-openbsd xvfb
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - name: Set up Geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Set up node
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: 12
      - name: Install yarn
        run: npm -g install yarn
      - name: Make dev-setup
        run: |
          make dev-setup db="${{ matrix.db-type }}" venv_bin=""
          make l10n venv_bin=""
          yarn add tslint
      - name: Linter
        run: ./node_modules/.bin/tslint "./nextcloudappstore/core/static/assets/**/*.ts"
      - name: Tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x8" make test venv_bin=""
      - name: Coverall
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
